<?php
/**
 * @author RAJERISON Julien
 */

/**
 * Class A
 */
final class A
{
    /**
     * @param $a
     * @param $b
     * @return float|int
     */
    final function doSomething($a, $b)
    {
        return $a * $b;
    }
}


/**
 * Class b return error final class not extended
 */
class B extends A
{
    // CLASS: may not inherit to final class
}

/**
 * Instanciation A to D
 *
 * Class Jul
 */
class Jul
{
    private $a;

    /**
     * d constructor.
     * Call A Method to constructor
     * @param A $a
     */
    public function __construct(A $a)
    {
        $this->a = $a;
    }

    /**
     * calc $a $b return not error
     */
    public function calcAb()
    {
        return $this->a->doSomething(1, 2);
    }

    final function is_jul()
    {
        return true;
    }
}

/**
 * Class Mickie
 */
class Mickie extends Jul
{
    /**
     * @return bool|void
     */
    public function is_jul()
    {
        // Cannot override final methode
    }

    /**
     * @return float|int
     */
    public function calcAb()
    {
        return parent::calcAb(); // TODO: Change the autogenerated stub
    }
}